model:
  type: TabVAEClassifier
  latent_dim: 32
  encoder: [256, 256, 128]
  decoder: [256, 256, 128]
  clf_head: [128, 64]
  dropout: 0.3
  beta_anneal: {start: 0.0, end: 0.7, epochs: 15}
  lambda_anneal: {start: 0.5, end: 1.0, epochs: 15}
  loss:
    recon_weighting: "inv_std"
    focal: {use: false, gamma: 2.0}
train:
  optimizer: {name: adamw, lr: 3e-4, weight_decay: 1e-4}
  batch_size: 256
  max_epochs: 100
  early_stop: {patience: 10, metric: "val_auprc", mode: "max"}
data:
  schema: "configs/schema_example.yaml"
  target: "in_hospital_mortality"
  imputation: "simple"
eval:
  calibration: {ece_bins: 15, temperature_scaling: true}
  tstr: {estimators: ["logreg", "xgboost"]}
